name: Maven CI/CD with Conditional ExtentReports Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Create ExtentReports Directory
        run: mkdir -p target/ExtentReports

      - name: Build and Test with Maven
        run: |
          mvn clean install
          mvn test -Dwebdriver.chrome.driver=/usr/bin/google-chrome -Dheadless=true
        env:
          MAVEN_OPTS: "-Xmx1024m"

      - name: List Target Directory
        run: ls -R target || echo "Target directory not found"

      - name: Check if ExtentReport Exists
        id: check_report
        run: |
          if [ -f target/ExtentReports/ExtentReport.html ]; then
            echo "Report found"
            echo "report_exists=true" >> $GITHUB_ENV
          else
            echo "Report not found"
            echo "report_exists=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push Report
        if: env.report_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f target/ExtentReports/ExtentReport.html
          git commit -m "Update ExtentReport"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
