name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Chrome installieren (f체r die Tests erforderlich)
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # 4. Maven-Abh채ngigkeiten cachen
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 5. Maven-Build ausf체hren und Tests im Headless-Modus durchf체hren
      - name: Build and Test with Maven
        run: mvn clean test -Dwebdriver.chrome.driver=/usr/bin/google-chrome -Dchrome.options.args="--headless,--no-sandbox,--disable-dev-shm-usage"


      # 6. HTML-Testberichte hochladen (ExtentReports)
      - name: Upload ExtentReports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: extentreports
          path: target/ExtentReports/ExtentReport.html
