name: Maven CI/CD with ExtentReports Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # 3. Chrome installieren
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # 4. Maven-Build und Tests ausführen
      - name: Build and Test with Maven
        run: |
          mvn clean install
          mvn test -Dwebdriver.chrome.driver=/usr/bin/google-chrome -Dheadless=true

      # 5. Änderungen im `target/ExtentReports`-Pfad committen und pushen
      - name: Commit and Push Report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add target/ExtentReports/ExtentReport.html
          git commit -m "Update ExtentReport"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
