name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Check out code
        uses: actions/checkout@v3

      # 2. Java einrichten
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Chrome installieren
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      # 4. Maven-Abhängigkeiten cachen
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 5. Maven-Build und Tests ausführen
      - name: Build and Test with Maven
        run: mvn clean test -Dwebdriver.chrome.driver=/usr/bin/google-chrome

      # 6. Testberichte bereitstellen (Surefire-Reports)
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports

      # 7. HTML-Testberichte hochladen (ExtentReports)
      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: html-report
          path: target/ExtentReports/ExtentReport.html

      # 8. Bericht auf GitHub Pages bereitstellen
      - name: Deploy to GitHub Pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: target/ExtentReports
